export interface GroceryProvider {
  id: string;
  name: string;
  logoColor: string;
  deliverySpeed: string;
  minOrder: string;
  popularFor: string;
  buildSearchUrl: (query: string) => string;
  buildBatchUrl?: (items: string[]) => string;
}

export const GROCERY_PROVIDERS: GroceryProvider[] = [
  {
    id: "instacart",
    name: "Instacart",
    logoColor: "#003d29",
    deliverySpeed: "30-60 mins",
    minOrder: "$10 min",
    popularFor: "Multi-store local supermarkets (Aldi, Costco, Publix, Safeway)",
    buildSearchUrl: (query: string) =>
      `https://www.instacart.com/store/s?k=${encodeURIComponent(query)}`,
    buildBatchUrl: (items: string[]) =>
      `https://www.instacart.com/store/s?k=${encodeURIComponent(items.join(" "))}`,
  },
  {
    id: "walmart",
    name: "Walmart Grocery",
    logoColor: "#0071dc",
    deliverySpeed: "Same-day or 1-hr express",
    minOrder: "$35 free delivery with +",
    popularFor: "Lowest everyday grocery prices & pantry staples",
    buildSearchUrl: (query: string) =>
      `https://www.walmart.com/search?q=${encodeURIComponent(query + " grocery")}`,
    buildBatchUrl: (items: string[]) =>
      `https://www.walmart.com/search?q=${encodeURIComponent(items.slice(0, 3).join(" "))}`,
  },
  {
    id: "amazon_fresh",
    name: "Amazon Fresh",
    logoColor: "#232f3e",
    deliverySpeed: "2-hour scheduled windows",
    minOrder: "$35 Prime members",
    popularFor: "Fresh produce, Whole Foods 365 brand, pantry essentials",
    buildSearchUrl: (query: string) =>
      `https://www.amazon.com/s?k=${encodeURIComponent(query)}&i=amazonfresh`,
  },
  {
    id: "kroger",
    name: "Kroger / Fred Meyer",
    logoColor: "#174289",
    deliverySpeed: "Same-day delivery",
    minOrder: "$35 min",
    popularFor: "Digital coupons & regional grocery chains",
    buildSearchUrl: (query: string) =>
      `https://www.kroger.com/search?query=${encodeURIComponent(query)}`,
  },
  {
    id: "target",
    name: "Target (Shipt)",
    logoColor: "#cc0000",
    deliverySpeed: "Same-day delivery",
    minOrder: "$35 for same-day",
    popularFor: "Good & Gather brand, organic items, essentials",
    buildSearchUrl: (query: string) =>
      `https://www.target.com/s?searchTerm=${encodeURIComponent(query + " grocery")}`,
  },
  {
    id: "doordash",
    name: "DoorDash Grocery",
    logoColor: "#eb1700",
    deliverySpeed: "25-45 mins (Fastest)",
    minOrder: "$12 min",
    popularFor: "Immediate convenience stores, local grocers, pharmacies",
    buildSearchUrl: (query: string) =>
      `https://www.doordash.com/search/store/${encodeURIComponent(query)}`,
  },
];

export interface MissingCartItem {
  id: string;
  name: string;
  amount: string;
  estimatedPrice: number;
  storeCategory: string;
  substituteOption?: string;
  mealTitle?: string;
  checked: boolean;
}

export function generateShoppingListText(items: MissingCartItem[]): string {
  if (items.length === 0) return "No missing items in shopping list.";

  const total = items.reduce((acc, i) => acc + (i.checked ? i.estimatedPrice : 0), 0);
  const checkedItems = items.filter((i) => i.checked);

  let text = `🛒 Smart Grocery Delivery List (${checkedItems.length} items - Est: $${total.toFixed(2)})\n`;
  text += `Generated by Fridge Meal AI Agent\n\n`;

  // Group by department
  const byCategory: Record<string, MissingCartItem[]> = {};
  for (const item of checkedItems) {
    const cat = item.storeCategory || "General Grocery";
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(item);
  }

  for (const [category, catItems] of Object.entries(byCategory)) {
    text += `[${category}]\n`;
    for (const item of catItems) {
      text += `• ${item.amount ? `${item.amount} ` : ""}${item.name} (~$${item.estimatedPrice.toFixed(2)})`;
      if (item.substituteOption) {
        text += ` (Sub: ${item.substituteOption})`;
      }
      text += `\n`;
    }
    text += `\n`;
  }

  text += `Total Estimated Cost: $${total.toFixed(2)}\n`;
  text += `Ready to order via Instacart, Walmart, or Amazon Fresh!`;

  return text;
}
